### ISSUE TITLE
Stream Reader

### ISSUE THREAD

**Issue by alangunning** [DaSpawn/exceljs#3]
Will it still be possible to pipe a stream to the reader instead of passing a filename?

**Comment by DaSpawn** [comment]
Yes, it will able to handle piped streams now, the zip module I used at first had forced the file read instead of stream.  I had to rewrite even further, the zip module would randomly choke on regular excel sheets with transform callback issues, plus it was read blocking

almost done, need to finish new zip integration

**Comment by alangunning** [comment]
Excellent!

**Comment by DaSpawn** [comment]
New streaming reader is complete for now, DaSpawn/xlsx-stream-reader
